### PR TITLE
新增 首頁 Route & Events Controller

### PR DESCRIPTION
**Pull request by Robeeerto**
新增 首頁 Route & Events Controller

### CODE REVIEW

**Review by SunWeiChou — APPROVED** [review]
LGTM

**Comment by skyee2021** [comment]
OK

**Review by skyee2021 — DISMISSED** [review]
OK

**Review by Weij28 — DISMISSED** [review]

**Comment by Weij28** [comment]
我也OK～

**Comment by Robeeerto** [comment]
新增 tailwind & foreman setting

**Review by SunWeiChou — APPROVED** [review]

**Review by FriedrichChiu — APPROVED** [review]
LGTM

**Comment by FriedrichChiu** [comment]
LGTM

**Review by skyee2021 — APPROVED** [review]

**Comment by hogaga** [comment]
ok

**Review by hogaga — APPROVED** [review]

**Review by Weij28 — APPROVED** [review]
Ok~~

**Pull request merged**
